"""empty message

Revision ID: 619d0b2ee975
Revises: 
Create Date: 2020-09-09 18:56:58.771758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619d0b2ee975'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aid', sa.Column('genre', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aid', 'genre')
    # ### end Alembic commands ###
